version: '3.4'
services:
  pApp:
    image: hanbitgaram/papp-cli:8.2.1
    container_name: "docker-pma"
    stop_signal: "sigkill"
    ports:
      - "127.0.0.1:10000:10000"
    volumes:
      - "./data/pma:/pma:rw"
      - "./data/app.php:/app.php"
      - "./data/php.ini:/etc/php/8.2/cli/php.ini"
    depends_on:
      - "mariadb"

  mariadb:
    build:
      context: "./files/mariadb"
      args:
        MYSQL_UID: 501
        MYSQL_GID: 501
    user: "501:501"
    restart: "always"
    container_name: "docker-mariadb"
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
      - "MYSQL_DATABASE=user"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=user"
    volumes:
      - "./data/mariadb:/var/lib/mysql:rw"